# Generated by Django 3.2.4 on 2021-06-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='relation',
            field=models.CharField(choices=[('GrandParent', 'GrandParent'), ('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Child', 'Child'), ('Grandchild', 'Grandchild'), ('Godchild', 'Godchild'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
