# Generated by Django 3.2.4 on 2021-06-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_beneficiary_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='email',
            field=models.EmailField(max_length=60, null=True, unique=True, verbose_name='email'),
        ),
    ]
