# Generated by Django 3.2.4 on 2021-06-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_beneficiary_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='user',
        ),
    ]
