# Generated by Django 3.2.4 on 2021-06-16 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210616_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=60, null=True, unique=True, verbose_name='email')),
                ('id_number', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customer')),
            ],
            options={
                'verbose_name': 'ID Number',
                'verbose_name_plural': 'ID Number',
            },
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.beneficiary'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
