# Generated by Django 3.2.4 on 2021-06-16 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210616_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'verbose_name': 'Beneficiery', 'verbose_name_plural': 'Beneficiaries'},
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='customer',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customer'),
        ),
    ]
