# Generated by Django 3.2.4 on 2021-06-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_task_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
