# Generated by Django 3.2.4 on 2021-06-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_task_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='owner',
            new_name='assignee',
        ),
    ]
